### ISSUE TITLE
This Maybe Violating the Twitter USer Policy Somehow

### ISSUE THREAD

**Issue by everbliss7** [caius/github_id#4]
Hi, Caius Durling-

I like your app by the way.

I used this app to tweet my GitHub id on twitter @everbliss7 and somehow, Twitter temporarily blocked my account stating that "This activity was suspicious and violated Twitter's Policy".

Blessing.

**Comment by caius** [comment]
Hey, I can't see these events being related sorry. Thanks for the heads up and I'm glad you like it.
