### ISSUE TITLE
Create co-authored-by from username

### ISSUE THREAD

**Issue by svrooij** [caius/github_id#5]
Your page to display the github user ID is great. I use it for generating the a `Co-authored-by` line in commits shared by 2 users. [more details](https://svrooij.io/2020/07/31/add-extra-author/)

Would be great if it would also display that, piece of text. It's formatted like: 

```plain
Co-authored-by: [name] <[githubID]+[githubUsername]@users.noreply.github.com>
# So for me that would be
Co-authored-by: Stephan van Rooij <1292510+svrooij@users.noreply.github.com>
```

I've created a sample page, but yours looked so much better..... https://svrooij.io/github-info.html

**Comment by caius** [comment]
Nice idea, but I'm not interested in adding extra complexity/information to the tool. Thanks for the idea though.
